import { test, expect } from '@playwright/test';

// test.use({
//     viewport: {
//         height: 1080,
//         width: 1920
//     }
// });

test('test', async ({ page }) => {
    test.setTimeout(150000);
    await page.goto('https://tftr.test.josce.mil/#/');
    await page.getByLabel('Username').click();
    await page.getByLabel('Username').fill('9677899107');
    await page.getByLabel('Password', { exact: true }).click();
    await page.getByLabel('Password', { exact: true }).fill('myTr!an!ng_$A!C_10-09');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.getByLabel('Primary Navigation').locator('a').filter({ hasText: 'Manage' }).click();
    await page.locator('a').filter({ hasText: 'Personnel' }).click();
    await page.getByRole('button', { name: 'Last Name, First Name' }).click();
    await page.getByRole('button', { name: 'All' }).click();
    await page.getByLabel('Name').locator('svg').click();
    await page.getByText('EDIPI').click();
    await page.getByPlaceholder('0000000000').click();
    await page.getByPlaceholder('0000000000').fill('9487857909');
    await page.getByRole('cell', { name: 'Dixon, Steven', exact: true }).click();
    await page.locator('a').filter({ hasText: 'Manage ITR' }).click();
    await page.getByLabel('Secondary Navigation').locator('a').nth(1).click();
    await page.getByText('Duties of the Deployment & Distribution Flight').click();
    await page.getByLabel('Start Date').click();
    await page.getByLabel('Nov 26,').click();
    await page.getByLabel('Task Complete Date').click();
    await page.getByLabel('Nov 26,').click();
    await page.getByRole('button', { name: 'Sign' }).click();
    await page.getByText('Responsibilities of the Deployment & Distribution Flight').click();
    await page.getByLabel('Start Date').click();
    await page.getByLabel('Nov 26,').click();
    await page.getByLabel('Task Complete Date').click();
    await page.getByLabel('Nov 26,').click();
    await page.getByRole('button', { name: 'Sign' }).click();
    await page.locator('a').filter({ hasText: 'Nicholas Taylor' }).click();
    await page.locator('a').filter({ hasText: 'Logout' }).click();
    await page.getByLabel('Username').click();
    await page.getByLabel('Username').fill('9487857909');
    await page.getByLabel('Password', { exact: true }).click();
    await page.getByLabel('Password', { exact: true }).fill('myTr!an!ng_$A!C_10-09');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.goto('https://tftr.test.josce.mil/#/Training/Profile');
    await page.locator('a').filter({ hasText: 'ITR' }).click();
    await page.getByText('Duties of the Deployment & Distribution Flight').click();
    await page.getByRole('button', { name: 'Sign' }).click();
    await page.locator('a').filter({ hasText: 'Steven Dixon' }).click();
    await page.locator('a').filter({ hasText: 'Logout' }).click();
    await page.getByLabel('Username').click();
    await page.getByLabel('Username').fill('9677899107');
    await page.getByLabel('Password', { exact: true }).click();
    await page.getByLabel('Password', { exact: true }).fill('myTr!an!ng_$A!C_10-09');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.getByLabel('Primary Navigation').locator('a').filter({ hasText: 'Manage' }).click();
    await page.locator('a').filter({ hasText: 'Product' }).click();
    await page.getByPlaceholder('Search for CFETP').click();
    await page.getByPlaceholder('Search for CFETP').fill('2t1');
    await page.getByText('2T1X1 Published: Nov 26,').click();
    await page.getByRole('button', { name: 'Edit Document' }).click();
    await page.getByLabel('Select All').check();
    await page.getByRole('button', { name: 'Add' }).click();
    await page.locator('#proposed-Task-96446-input').check();
    await page.locator('cfetp-revision-task-list').getByText('Duties of the Deployment & Distribution Flight').click();
    await page.getByLabel('Training Reference').click();
    await page.getByRole('button', { name: 'Save' }).click();
    await page.locator('cfetp-revision-task-list').getByText('Responsibilities of the Deployment & Distribution Flight - TR').click();
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Confirm' }).click();
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByRole('button', { name: 'Publish' }).click();
    await page.getByLabel('Published to e-pubs on').check();
    await page.getByLabel('I understand this document').check();
    await page.getByLabel('I agree to release this').check();
    await page.getByPlaceholder('DD-MMM-YY').click();
    await page.getByLabel('Nov 26,').click();
    await page.getByRole('button', { name: 'Upload' }).click();
    await page.locator('a').filter({ hasText: 'Manage' }).click();
    await page.locator('a').filter({ hasText: 'Personnel' }).click();
    await page.getByRole('button', { name: 'Last Name, First Name' }).click();
    await page.getByRole('button', { name: 'All' }).click();
    await page.locator('#mat-select-value-9').click();
    await page.getByRole('option', { name: 'EDIPI' }).click();
    await page.getByPlaceholder('0000000000').click();
    await page.getByPlaceholder('0000000000').fill('9487857909');
    await page.getByRole('cell', { name: 'Dixon, Steven', exact: true }).click();
    await page.locator('a').filter({ hasText: 'Manage ITR' }).click();
    await page.locator('#PageLoadingWrapper').click();
    await page.getByText('Duties of the Deployment & Distribution Flight').click();
    await page.getByRole('button', { name: 'Decertify' }).click();
    await page.getByText('Unassigned').click();
    await page.getByText('Trainer').click();
    await page.getByRole('button', { name: 'Confirm' }).click();
    await page.locator('a').filter({ hasText: 'Journal' }).click();
    await page.locator('journal-signer-box:nth-child(2) > .ProfileCard__Data > .SignerBox__Check > .SignerBox__Checkbox').first().click();
    await page.locator('journal-card:nth-child(2) > .JournalCard > .JournalCard__Action > .JournalCard__Signatures > journal-signer-box:nth-child(2) > .ProfileCard__Data > .SignerBox__Check > .SignerBox__Checkbox').click();
    await page.getByRole('button', { name: 'Sign' }).click();
    await page.getByRole('button', { name: 'Delete' }).first().click();
    await page.getByLabel('Yes').click();
    await page.getByRole('button', { name: 'Delete' }).first().click();
    await page.getByLabel('Yes').click();
    await page.getByRole('button', { name: 'Delete' }).click();
    await page.getByLabel('Yes').click();
    await page.locator('a').filter({ hasText: 'Nicholas Taylor' }).click();
    await page.locator('a').filter({ hasText: 'Logout' }).click();
});